----------------------------------
STARTING FRAME 00001
----------------------------------
file.coping
file.coping
file.nek5000
pv.load_VisItNek5000
pv.create_Clip
pv.save_Source
pv.load_CGNS
Traceback (most recent call last):
  File "/dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/paraview-prebuild/5.8.0_mesa-gcc-dpwpicy/lib/python3.7/site-packages/paraview/servermanager.py", line 472, in __setattr__
    setter = getattr(self.__class__, name)
AttributeError: type object 'CGNSSeriesReader' has no attribute 'Bases'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/paraview-prebuild/5.8.0_mesa-gcc-dpwpicy/lib/python3.7/site-packages/paraview/servermanager.py", line 478, in __setattr__
    _bc.setattr(self, name, value)
  File "/dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/paraview-prebuild/5.8.0_mesa-gcc-dpwpicy/lib/python3.7/site-packages/paraview/_backwardscompatibilityhelper.py", line 335, in setattr
    raise AttributeError()
AttributeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    clip = pv.load_CGNS(f"{temp_folder}/clip.cgns", ['velocity', 'velocity_mag'], ['Base_Volume_Elements'])
  File "/hppfs/work/pn73fu/di82nid/run/jet_pvpython/paraview_functions.py", line 23, in load_CGNS
    source.Bases = bases
  File "/dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/paraview-prebuild/5.8.0_mesa-gcc-dpwpicy/lib/python3.7/site-packages/paraview/servermanager.py", line 485, in __setattr__
    "to add this attribute.")
AttributeError: Attribute Bases does not exist.  This class does not allow addition of new attributes to avoid mistakes due to typos. Use add_attribute() if you really want to add this attribute.
